name: Get latest release version
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch release version
        run: | 
          name=$(curl -sL https://api.github.com/repos/dweymouth/supersonic/releases/latest | jq -r ".name"); \
          [ "$name" != "null" ] && sed -i "s/\(version\) .*/\1 \"$name\"/" Casks/supersonic.rb
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit updated release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Automatically update version"
          git push
